### ISSUE TITLE
Combine landing page and home page

### ISSUE THREAD

**Issue by ghost** [sceptix-club/sceptix-website#2]
## Merge the landing page into the home page such that the home page's contents appear right below the landing animation.
![land-image](https://github.com/sceptix-club/sceptix-website/assets/59310023/4af43c87-fbb7-4c6e-823c-b89bbab3dd4a)
![home-image](https://github.com/sceptix-club/sceptix-website/assets/59310023/8382a451-df2d-4bfe-a812-1e8fdc632de3)

- The resulting sidebar would have three icons only.
- It also makes navigation to the landing page more sensible.

**Comment by Vyshnav001** [comment]
@septicalls  this issue is fixed and the code has been pushed to the main branch already
